### ISSUE TITLE
Seeds use default values for missing cells instead of Nullable()

### ISSUE THREAD

**Issue by mlazowik** [ClickHouse/dbt-clickhouse#116]
We'd like to seed CSVs with some cells intentionally missing, and store them as nulls in the db. However, the table schema that gets created does not have Nullable types and default values are inserted for empty cells. For example we get January 1, 1970 for empty dates.

Version `1.2.1`, but as far I see nothing changed related to this in the newer versions.

**Comment by genzgd** [comment]
This can be managed through your dbt configuration.  You can specify explicit column types in your schema or project file:  https://docs.getdbt.com/reference/seed-configs

Here's an example from our enhanced seed test:

```yaml
version: 2

seeds:
  - name: empty
    config:
      column_types:
        val2: Nullable(UInt32)
        str1: Nullable(String)
```
