### ISSUE TITLE
Connections incorrectly re-use session ids on creation (Session is locked Error)

### ISSUE THREAD

**Issue by ikeniborn** [ClickHouse/dbt-clickhouse#127]
When I run dbt Concurrency: 4 threads I get 
> :HTTPDriver for http://**.**.**.***:8123 returned response code 500)
16:09:35     Code: 373. DB::Exception: Session is locked by a concurrent client. (SESSION_IS_LOCKED) (version 22.12.2.25 (official build))

in terminal, but in database process is run.
I get messge after about 10 minutes after start.

Core:
  - installed: 1.3.1
  - latest:    1.3.2 - Update available!

Plugins:
  - postgres:   1.3.1 - Update available!
  - clickhouse: 1.3.1 - Update available!
```yml
clickhouse:
  target: default
  outputs:
    default:
      driver: http
      type: clickhouse
      schema: default
      user: default
      password: ''
      #optional fields
      port: 8123
      host: ***.***.***.***
      verify: False
      secure: False
      connect_timeout: 60
      compression: 'gzip'
      threads: 4
      send_receive_timeout: 100000
      check_exchange: False
```
