### ISSUE TITLE
Missing identifier quoting

### ISSUE THREAD

**Issue by apisarenco** [ClickHouse/dbt-clickhouse#144]
### Describe the bug
Identifiers are not quoted even when the setting is on

### Steps to reproduce
1. Have as source databases that contain non-alphanumeric characters (ex. UUID as database name)
2. Have queries that source from those tables
3. Compile the model and behold! not quoted strings.

### Expected behaviour
Database names and table names should be quoted when configured

### Code examples, such as models or profile settings

```
version: 2

sources:
  - name: t01
    schema: "a6bf4b3f-17ee-4ae3-b769-acc2ffe0d708"
    tables: &tables
      - name: the_table
      - name: the_other_table
    quoting: &quoting
      database: true
      schema: true
      identifier: true

  - name: t02
    schema: "6410659e-85c7-413b-b952-aca7fd639788"
    tables: *tables
    quoting: *quoting
```

```
{{
    config({
        "materialized": "table",
        "engine": "MergeTree()",
        "schema": "dev",
        "order_by": '(id)'
    })
}}
{% set tenants =  ['t01', 't02'] %}
{% set data_sources = [] %}
{% for tenant in tenants %}
{% do data_sources.append(source(tenant, 'the_table')) %}
{% endfor %}
WITH cte AS (
    {{ dbt_utils.union_relations(data_sources) }}
)
SELECT * FROM cte
```
