### ISSUE TITLE
DbtRuntimeError.__init__() missing 1 required positional argument: 'msg'

### ISSUE THREAD

**Issue by brendavarguez** [ClickHouse/dbt-clickhouse#169]
### Describe the bug

I am having this error message when trying to build both materialized tables and incremental tables. The funny thing is that sometimes I am able to build the tables and sometimes I get this error message.

```
DbtRuntimeError.__init__() missing 1 required positional argument: 'msg'
    
    > in macro materialization_table_clickhouse (macros/materializations/table.sql)
    > called by model stg_transaction_event_card (models/prd/staging/stg_transaction_event_card.sql)
```

When successful, the table is build with all the data. But when it fails, an empty table is created in my database.

#### For materialized tables
1. `profiles.yaml`
```
local_clickhouse:
      type: clickhouse
      schema: warehouse_dev
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASS') }}"
      port: 9000
      host: localhost
      cluster: default
      retries: 1
      connect_timeout: 10
      send_receive_timeout: 3600 # 1hr
```
2. `stg_transaction_event_card.sql` example code:
```
{{
    config(
        materialized = "table",
        engine = "ReplicatedMergeTree",
        unique_key = "transaction_id",
        pre_hook = "TRUNCATE TABLE IF EXISTS {{ this }} ON CLUSTER default",
        indexes=[
          {'columns': ['transaction_id'], 'type': 'btree', 'unique': True },
          {'columns': ['last_mod'], 'type': 'btree'}
        ]
    )
}}

WITH txns_events AS (
    SELECT
        col1,
        col2,
        col3
    FROM postgresql('host:port', 'db_name', 'table_name', 'db_user', 'db_password', 'schema')
)

SELECT
    col1,
    col2,
    col3
FROM txns_events
```

#### For incremental tables
1. `profiles.yaml`
```
local_clickhouse:
      type: clickhouse
      schema: warehouse_dev
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASS') }}"
      port: 9000
      host: localhost
      cluster: default
      retries: 1
      connect_timeout: 10
      send_receive_timeout: 3600 # 1hr
      use_lw_deletes: true
```

2. `stg_transaction_event_card.sql` example code:
```
{{
    config(
        materialized = "incremental",
        unique_key = "transaction_id",
        indexes=[
          {'columns': ['transaction_id'], 'type': 'btree', 'unique': True },
          {'columns': ['last_mod'], 'type': 'btree'}
        ]
    )
}}

WITH txns_events AS (
    SELECT
        col1,
        col2,
        col3
    FROM postgresql('host:port', 'db_name', 'table_name', 'db_user', 'db_password', 'schema')

    {% if is_incremental() %}

         AND (last_mod > (SELECT max(last_mod) FROM {{ this }}))

    {% endif %}
)

SELECT
    col1,
    col2,
    col3
FROM txns_events
```

#### Environment
* dbt version: `dbt-core=1.4.6`
* dbt-clickhouse version: `dbt-clickhouse=1.4.2`
* Python version: `Python=3.11.4`
* Operating system: M1 Mac
