### ISSUE TITLE
Config `rename_response_column` to clickhouse connection

### ISSUE THREAD

**Issue by mtieuso** [ClickHouse/dbt-clickhouse#176]
I am trying this query

```
with 
	x as (select 1 as a, 2 as id),
	y as (select 1 as a, 3 as id)
select
	y.a,
	y.id
from 
	x
	join y using (a)
```

 And the result is

 ```
 y.a|y.id|
---+----+
  1|   3|
  ```

Is there any way/config to remove automatically the alias `y.` in the final response (without using `y.a  as a`)?

In DBeaver, I can config rename_response_column=REMOVE_PREFIX in database connection.
but when I tried config in clickhouse's profile:

```
    ch:
      type: clickhouse
      name: ch
      schema: ch
      host: "{{ env_var('DBT_ENV_CH_HOST') }}"
      port: "{{ env_var('DBT_ENV_CH_PORT', '8123') | int }}"
      user: "{{ env_var('DBT_ENV_SECRET_CH_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_CH_PASSWORD') }}"
      secure: False
      custom_settings:
        rename_response_column: REMOVE_PREFIX
```

There is an error:

```
10:35:36  Encountered an error:
Database Error
  Setting rename_response_column is unknown or readonly
```

How can I config this setting properly?
