### ISSUE TITLE
Custom Settings for Models

### ISSUE THREAD

**Issue by rjoelnorgren** [ClickHouse/dbt-clickhouse#181]
**Is your feature request related to a problem? Please describe.**
I would like to apply custom settings to my model configs.

As a concrete example, in some cases I need to export tables that are compatible with Spark. By default, ClickHouse parquet format is not compatible and the following settings are required for the S3 table:
```sql
create table s3_table(...)
engine = S3(..., 'Parquet')
settings
    output_format_parquet_string_as_string=1,
    output_format_parquet_compression_method='snappy'
;
```

That said, I do not necessarily want these settings applied to all queries in my target.

**Describe the solution you'd like**
Add a custom_settings key to the model config:
```yaml
models:
  - name: s3_table
    config:
      engine: S3
      custom_settings:
        output_format_parquet_string_as_string: 1
        output_format_parquet_compression_method: snappy
```

**Describe alternatives you've considered**
Currently working around this and the [codec limitation](https://github.com/ClickHouse/dbt-clickhouse/issues/88) using a custom macro that manages ddl using the on-run-start hook for the project. But it's pretty hacky and does not integrate well with much of dbt's core functionality.
