### ISSUE TITLE
dbt test command recreates the whole database

### ISSUE THREAD

**Issue by kmogilevskii** [ClickHouse/dbt-clickhouse#235]
I have a dbt model that runs certain transformations incrementally on the ClickHouse table. Also, I wrote a generic dbt test to run after the model.

The model's config is as following:

```
{{ config (
    tags="my_tag",
    materialized = "incremental",
    order_by = ["col1", "col2", "col3"],
    partition_by = ['toYYYYMMDD("date_column")'],
)}}
```
The model's test defined in the schema.yml file like this

```
models:
  - name: model_name
    description: model description
    config:
      materialized: table
    columns:
      - name: date_column
        tests:
          - not_null:
              config:
                where: date_column > toStartOfMonth(today())
          - generic_test_name:
              arg1: 1
              arg2: MONTH
              config:
                severity: error
                error_if: ">100"
                warn_if: ">0"
```
dbt test command in case of the error (more than 100 records produced) saves the results in the separate database and table in it (ClickHouse doesn't have a notion of schema, just database and tables) My problem is that I can't find in the documentation how to prevent it to recreate a database and the tables in it for the results of the test run in case there were an actual error. It always recreates it on every run and my user that's gonna run it won't have the permissions to create a database. Plus, I want it to append the error records incrementally to the existing tables as well.
