### ISSUE TITLE
Model query_settings not honored for incremental models with contracts

### ISSUE THREAD

**Issue by rjoelnorgren** [ClickHouse/dbt-clickhouse#277]
### Describe the bug
When contracts are configured for a model, the clickhouse__insert_into macro does not interpolate query_settings configured for that model.

### Steps to reproduce
1. Create model with contracts
2. Configure query_settings on the model
3. Run the mode
4. Observe the configured settings are missing from system.query_log.Settings for the query inserting into the model.

### Expected behaviour
The query settings are used for the model.

**Comment by BentsiLeviav** [comment]
Hi @rjoelnorgren

Thanks for opening this issue.
I actually managed to see the settings when following your steps to reproduce instructions.  This is my setup:

schema.yml file:
```yml
version: 2

models:
  - name: test
    description: test issue 227 + cr 228
    config:
      materialized: incremental
      query_settings: {"allow_experimental_analyzer":0}
      order_by: rand_trip_id
      unique_key: rand_trip_id
      on_schema_change: fail
      contract:
        enforced: true
    columns:
      - name: rand_trip_id
        data_type: UInt8
      - name: key2
        data_type: string
```

test.sql (the model):
```sql
select 1 as rand_trip_id, 'test' as key2
```

The generated insert into query:
```sql
     insert into `default`.`test__dbt_tmp` ("rand_trip_id", "key2")
        select "rand_trip_id", "key2"
        from `default`.`test__dbt_new_data`
      
            -- settings_section
            SETTINGS  allow_experimental_analyzer=0
```

After running this, I queried `system.query_log` using this query:
```sql
select Settings from system.query_log
         where query like '%dbt%' and query_kind = 'Insert' and query like '%allow_experimental_analyzer%'
order by query_start_time desc
```

And got the following line:
```python
{'distributed_foreground_insert': '1', 'http_zlib_compression_level': '3', 'send_progress_in_http_headers': '1', 'http_headers_progress_interval_ms': '120000', 'join_use_nulls': '1', 'allow_experimental_analyzer': '0', 'mutations_sync': '2', 'allow_nondeterministic_mutations': '1'}
```

My ClickHouse version is: `23.10.6.60`
My ClickHouse DBT version is: ` 1.7.11`
Python version: `3.9.6`

Could you provide more information regarding your setup and scenario? Because for the described setup - everything works well.
