### ISSUE TITLE
Can not connect clickhouse docker by ourselves

### ISSUE THREAD

**Issue by hueiyuan** [ClickHouse/dbt-clickhouse#300]
### Describe the bug
We build clickhouse cluster on our localhost with docker, and we also confirm that is work.
But if we use dbt to connect clickhouse, which always shows `Error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) executing HTTP request attempt 2 (http://localhost:8123)`
Does have any ideas about it? Thank you.

### Expected behaviour
In general, should connect to clickhouse successfully.

### Code examples, such as models or profile settings
```yaml
## profiles.yaml
dbt_clickhouse:
  outputs:
    dev:
      type: clickhouse
      threads: 4 
      host: localhost
      driver: http
      port: 8123 
      user: deafult
      password: default1234
      schema: ipp_default 
      cluster: ck_cluster
      cluster_mode: true
      send_receive_timeout: 1000
  target: dev
```

### dbt and/or ClickHouse server logs
```
============================== 17:41:54.014575 | 35d53beb-77c8-4f74-9b32-b3c1650c3274 ==============================
[0m17:41:54.014575 [info ] [MainThread]: Running with dbt=1.8.2
[0m17:41:54.014928 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/mars_su/personal/side-projects/dbt-clickhouse/dbt_clickhouse', 'log_path': '/Users/mars_su/personal/side-projects/dbt-clickhouse/dbt_clickhouse/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:41:54.027915 [info ] [MainThread]: dbt version: 1.8.2
[0m17:41:54.028201 [info ] [MainThread]: python version: 3.9.6
[0m17:41:54.028401 [info ] [MainThread]: python path: /Library/Developer/CommandLineTools/usr/bin/python3
[0m17:41:54.028589 [info ] [MainThread]: os info: macOS-14.3.1-arm64-arm-64bit
[0m17:41:54.071528 [info ] [MainThread]: Using profiles dir at /Users/mars_su/personal/side-projects/dbt-clickhouse/dbt_clickhouse
[0m17:41:54.071828 [info ] [MainThread]: Using profiles.yml file at /Users/mars_su/personal/side-projects/dbt-clickhouse/dbt_clickhouse/profiles.yml
[0m17:41:54.072036 [info ] [MainThread]: Using dbt_project.yml file at /Users/mars_su/personal/side-projects/dbt-clickhouse/dbt_clickhouse/dbt_project.yml
[0m17:41:54.072822 [info ] [MainThread]: adapter type: clickhouse
[0m17:41:54.073120 [info ] [MainThread]: adapter version: 1.8.0
[0m17:41:54.130310 [info ] [MainThread]: Configuration:
[0m17:41:54.130602 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m17:41:54.130795 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m17:41:54.130975 [info ] [MainThread]: Required dependencies:
[0m17:41:54.131692 [debug] [MainThread]: Executing "git --help"
[0m17:41:54.160606 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:41:54.161192 [debug] [MainThread]: STDERR: "b''"
[0m17:41:54.161446 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:41:54.161662 [info ] [MainThread]: Connection:
[0m17:41:54.161917 [info ] [MainThread]:   driver: http
[0m17:41:54.162099 [info ] [MainThread]:   host: localhost
[0m17:41:54.162271 [info ] [MainThread]:   port: 8123
[0m17:41:54.162438 [info ] [MainThread]:   user: deafult
[0m17:41:54.162612 [info ] [MainThread]:   schema: ipp_default
[0m17:41:54.162778 [info ] [MainThread]:   retries: 1
[0m17:41:54.162944 [info ] [MainThread]:   database_engine: None
[0m17:41:54.163114 [info ] [MainThread]:   cluster_mode: False
[0m17:41:54.163279 [info ] [MainThread]:   secure: False
[0m17:41:54.163439 [info ] [MainThread]:   verify: True
[0m17:41:54.163836 [info ] [MainThread]:   connect_timeout: 10
[0m17:41:54.164030 [info ] [MainThread]:   send_receive_timeout: 1000
[0m17:41:54.164197 [info ] [MainThread]:   sync_request_timeout: 5
[0m17:41:54.164359 [info ] [MainThread]:   compress_block_size: 1048576
[0m17:41:54.164521 [info ] [MainThread]:   compression: 
[0m17:41:54.164689 [info ] [MainThread]:   check_exchange: True
[0m17:41:54.164853 [info ] [MainThread]:   custom_settings: None
[0m17:41:54.165017 [info ] [MainThread]:   use_lw_deletes: False
[0m17:41:54.165178 [info ] [MainThread]:   allow_automatic_deduplication: False
[0m17:41:54.165650 [info ] [MainThread]: Registered adapter: clickhouse=1.8.0
[0m17:41:54.170465 [debug] [MainThread]: Acquiring new clickhouse connection 'debug'
[0m17:41:54.170999 [debug] [MainThread]: Opening a new connection, currently in state init
[0m17:41:54.804759 [debug] [MainThread]: dbt_clickhouse adapter: Got a retryable error when attempting to open a clickhouse connection.
1 attempts remaining. Retrying in 1 seconds.
Error:
Error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) executing HTTP request attempt 2 (http://localhost:8123)
[0m17:41:55.816606 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m17:41:55.817820 [info ] [MainThread]: [31m1 check failed:[0m
[0m17:41:55.818482 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) executing HTTP request attempt 2 (http://localhost:8123)

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m17:41:55.824930 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 1.8733028, "process_user_time": 2.706906, "process_kernel_time": 0.485744, "process_mem_max_rss": "152256512", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:41:55.826976 [debug] [MainThread]: Command `dbt debug` failed at 17:41:55.826687 after 1.88 seconds
[0m17:41:55.827947 [debug] [MainThread]: Connection 'debug' was left open.
[0m17:41:55.828618 [debug] [MainThread]: On debug: No close available on handle
[0m17:41:55.829257 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1029e3fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1341a1dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1341a1e50>]}
[0m17:41:55.830156 [debug] [MainThread]: Flushing usage events

```

#### Environment
* dbt version: 1.8.2
* dbt-clickhouse version: 1.8.0
* clickhouse-driver version: 0.2.7
* clickhouse-connect version (if using http):  0.7.14
* Python version: 3.9
* Operating system: MacOS

#### ClickHouse server
* ClickHouse Server version: 24.4.3-alpine

**Comment by simpl1g** [comment]
Can you please share your docker-compose file? I don't any have any issues with it, we do have CH dev cluster in compose. Are you running dbt from localhost or also from docker image?

**Comment by hueiyuan** [comment]
@simpl1g  Thanks for your reply.
About clickhouse docker-compose file is following:
```yaml
version: '3'

services:
  keeper:
    image: zookeeper:3.7
    container_name: keeper
    hostname: keeper
    networks:
      - ch_replicated
    volumes:
      - ${PWD}/ck/keeper:/etc/clickhouse-keeper
  clickhouse01:
    image: clickhouse/clickhouse-server:24.4.3-alpine
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      - ch_replicated
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${PWD}/ck/clickhouse01:/etc/clickhouse-server
    depends_on:
      - keeper
  clickhouse02:
    image: clickhouse/clickhouse-server:24.4.3-alpine
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      - ch_replicated
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ${PWD}/ck/clickhouse02:/etc/clickhouse-server
    depends_on:
      - keeper

networks:
  ch_replicated:
    driver: bridge
```

Additionally, my dbt is running on my localhost (through pip install )instead of docker image.
