### ISSUE TITLE
dbt Unit Tests fail to run

### ISSUE THREAD

**Issue by ricardo-barreira** [ClickHouse/dbt-clickhouse#304]
### Describe the bug
dbt-core introduced unit testing framework in version 1.8. When attempting to use this feature with the dbt-clickhouse plugin, it fails.
### Steps to reproduce
1. Create a simple dbt model:
```
{{ config(
    materialized='table'
    )
}}

select col1, sum(col2) as col2
from {{ ref('test_seed') }}
group by 1

```
3. Create a unit_tests.yaml file under your models folder:
```
unit_tests:
  - name: simple_test
    model: unit_test_model
    given:
      - input: ref('test_seed')
        rows:
          - { col1: a, col2: 1 }
          - { col1: a, col2: 1 }
    expect:
      rows:
        - { col1: a, col2: 2 }
```
4. Run the unit test
`dbt test --select test_type:unit`

#### Initial error:
```
Runtime Error in unit_test simple_test (models/staging/unit_tests.yaml)
  An error occurred during execution of unit test 'simple_test'. There may be an error in the unit test definition: check the data types.
   Database Error
    HTTPDriver for https://clickhouse-server.com:19319 returned response code 500)
     Code: 36. DB::Exception: Engine Memory doesn't support PARTITION_BY, PRIMARY_KEY, ORDER_BY or SAMPLE_BY clauses. Currently only the following engines have support for the feature: [S3, OSS, MaterializedPostgreSQL, ReplicatedVersionedCollapsingMergeTree, MergeTree, ReplacingMergeTree, ReplicatedSummingMergeTree, VersionedCollapsingMergeTree, ReplicatedReplacingMergeTree, ReplicatedGraphiteMergeTree, ReplicatedMergeTree, SummingMergeTree, ReplicatedCollapsingMergeTree, GraphiteMergeTree, CollapsingMergeTree, COSN, ReplicatedAggregatingMergeTree, AggregatingMergeTree]. (BAD_ARGUMENTS) (version 23.8.8.1)

```
This issue arises from the create_table_or_empty macro trying to pass invalid arguments (order by and partition by) to a temporary table creation query. After removing the problematic lines:

```
Runtime Error
ClickHouse exception:  Expecting value: line 1 column 1 (char 0)
```
### Expected behaviour
Unit test should run successfully

#### Environment
* dbt version: 
* dbt-clickhouse version:
* clickhouse-driver version (if using native)
* clickhouse-connect version (if using http):
* Python version:
* Operating system:

#### ClickHouse server
* ClickHouse Server version: 23.8.8.1
