### ISSUE TITLE
Field name annotation encoding error

### ISSUE THREAD

**Issue by Jackliebao** [ClickHouse/dbt-clickhouse#308]
When the field annotation field name is in Chinese, the following error will be reported

```
  - name: season_product_predict_seller_sku
    description: "season_data"
    config:
      engine: 'MergeTree'
      unique_key: 'info, update_time'
    columns:
      - name: 年趋势变化率
        description: rate of year
```

```
   Code: 62. DB::Exception: Syntax error: failed at position 352 ('\xe5') (line 6, col 85): 年趋势变化率
    $dbt_comment_literal_block$rate of year$dbt_comment_literal_block$

    . Unrecognized token: '\xe5'. (SYNTAX_ERROR) (version 24.4.1.2088 (official build))
  compiled Code at target\run\elt\models\sql_model\store_data\season_product_predict_seller_sku.sql
```

Currently, English fields are used instead of Chinese fields,
Can Chinese fields be supported in the future?
