### ISSUE TITLE
Encoding issues with column name annotations

### ISSUE THREAD

**Issue by Jackliebao** [ClickHouse/dbt-clickhouse#309]
### Describe the bug
When setting the field name to Chinese, the following error will be reported：
```
  - name: season_product_predict_seller_sku
    description: "season_data"
    config:
      engine: 'MergeTree'
      unique_key: 'info, update_time'
    columns:
      - name: 年趋势变化率
        description: rate of year
```
```
   Code: 62. DB::Exception: Syntax error: failed at position 352 ('\xe5') (line 6, col 85): 年趋势变化率
    $dbt_comment_literal_block$rate of year$dbt_comment_literal_block$

    . Unrecognized token: '\xe5'. (SYNTAX_ERROR) (version 24.4.1.2088 (official build))
  compiled Code at target\run\elt\models\sql_model\store_data\season_product_predict_seller_sku.sql
```
Currently, English fields are used instead of Chinese fields,
Can Chinese fields be supported in the future？
#### Environment
* dbt version:1.2.1
* dbt-clickhouse version:1.8.0
* clickhouse-driver version (if using native)
* clickhouse-connect version (if using http):
* Python version:3.12
* Operating system:Linux,windows

#### ClickHouse server
* ClickHouse Server version: 24.4.1.2088
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
