### ISSUE TITLE
SQL security and definer logic

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/dbt-clickhouse#359]
Starting from v.24.2 ClickHouse have **sql security** and **definer** logic (for view)

https://clickhouse.com/docs/en/sql-reference/statements/create/view#sql_security

It would be greate, to have this options for **View** materialization at dbt-clickhouse

**Comment by Baitur5** [comment]
will it be available in the next version?

**Comment by Baitur5** [comment]
There is a way to do it using **post_hook**:
```yml
  - name: pvw_sp_app_analytics
    config:
      materialized: view
      post_hook: "ALTER TABLE {{this}} MODIFY SQL SECURITY DEFINER DEFINER='user'"
```
