### ISSUE TITLE
Invalid setting when creating temporary tables with `ON CLUSTER`

### ISSUE THREAD

**Issue by shachibista** [ClickHouse/dbt-clickhouse#366]
Hi!

When trying to create a temporary table with the `cluster` property set, creating temporary tables with `Engine=Memory` passes the `replicated_deduplication_window` setting which is invalid. It seems that the `replicated_deduplication_window` setting only checks for [the materialization type](https://github.com/ClickHouse/dbt-clickhouse/blob/51bf0e1279b89856fdf2a50791d50e2b85b1fe18/dbt/adapters/clickhouse/dbclient.py#L115-L116) but does not check the `Engine` which it should.

I think that the [`update_model_settings`](https://github.com/ClickHouse/dbt-clickhouse/blob/51bf0e1279b89856fdf2a50791d50e2b85b1fe18/dbt/adapters/clickhouse/dbclient.py#L153-L159) method should accept engine type and only allow settings that are available for each engine.

Seeing this issue when trying to run https://github.com/elementary-data/dbt-data-reliability because it tries to create a [temporary table](https://github.com/elementary-data/dbt-data-reliability/blob/d3777b95230df68579705a6088e09d846b21f0db/macros/utils/table_operations/delete_and_insert.sql#L9) when artifacts change.

### Steps to reproduce
1. Setup a clickhouse multi-node cluster.
2. Configure with `cluster: "{cluster}"' in profiles
3. Run the elementary bootstrap model `dbt run -m elementary`

### Expected behaviour

No errors should be expected. The temporary table should be created in the connected node in memory.

### Code examples, such as models or profile settings

```yaml
# profiles.yml
project_name:
  target: local
  outputs:
    local:
      type: clickhouse
      driver: native
      schema: "{{ env_var('DBT_SCHEMA') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASS') }}"
      port: 9000
      cluster: "{cluster}"
      cluster_mode: true
      check_exchange: false
```

```yaml
# packages.yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.2.0

packages:
  - package: elementary-data/elementary
    version: 0.15.2
```

```yaml
# dbt_project.yml
name: 'project_name'
version: '1.0.0'

profile: 'project_name'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets: 
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: elementary
    search_order: ['project_name', 'elementary']

models:
  +engine: ReplicatedMergeTree

  elementary:
    +engine: ReplicatedMergeTree
    edr:
      system:
        enabled: false
      data_monitoring:
        enabled: false # Doesn't yet work because stddev is not available and cannot be overridden.

seeds:
  +engine: ReplicatedMergeTree

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: true
```

```sql
# macros/current_timestamp.sql
{% macro clickhouse__edr_current_timestamp() -%}
    now(timezone())
{%- endmacro -%}

{% macro clickhouse__edr_current_timestamp_in_utc() -%}
    now()
{%- endmacro -%}
```

### dbt and/or ClickHouse server logs

```
[0m17:24:58.632265 [debug] [Thread-1 (]: dbt_clickhouse adapter: Error running SQL: /* {"app": "dbt", "dbt_version": "1.8.6", "profile_name": "opti_analytics", "target_name": "local", "node_id": "model.elementary.dbt_models"} */

    
  
    
    
    

    create temporary table `dbt_models__tmp_20241010152458544783`
        engine Memory
        
                    -- end_of_sql
                    SETTINGS  replicated_deduplication_window=0

                    
        as (
          
        SELECT
        
            *
        
        FROM `project_name`.`dbt_models`
        WHERE 1 = 0
    
        )
  
  
[0m17:24:58.645419 [debug] [Thread-1 (]: Database Error in model dbt_models (models/edr/dbt_artifacts/dbt_models.sql)
  Code: 115.
  DB::Exception: Unknown setting 'replicated_deduplication_window': for storage Memory. Stack trace:
  
  0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc3f2c8
  1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007a8dc7c
  2. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000007a8d858
  3. DB::BaseSettingsHelpers::throwSettingNotFound(std::basic_string_view<char, std::char_traits<char>>) @ 0x000000000ea38e4c
  4. DB::BaseSettings<DB::memorySettingsTraits>::set(std::basic_string_view<char, std::char_traits<char>>, DB::Field const&) @ 0x000000000f1442c4
  5. DB::MemorySettings::loadFromQuery(DB::ASTStorage&) @ 0x000000000ff94e40
  6. std::shared_ptr<DB::IStorage> std::__function::__policy_invoker<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerStorageMemory(DB::StorageFactory&)::$_0, std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) (.llvm.1794116773610321499) @ 0x000000001008a0f8
  7. DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel) const @ 0x000000000fffac7c
  8. std::shared_ptr<DB::IStorage> std::__function::__policy_invoker<std::shared_ptr<DB::IStorage> (DB::StorageID const&)>::__call_impl<std::__function::__default_alloc_func<DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel)::$_0, std::shared_ptr<DB::IStorage> (DB::StorageID const&)>>(std::__function::__policy_storage const*, DB::StorageID const&) @ 0x000000000f609ac4
  9. DB::TemporaryTableHolder::TemporaryTableHolder(std::shared_ptr<DB::Context const>, std::function<std::shared_ptr<DB::IStorage> (DB::StorageID const&)> const&, std::shared_ptr<DB::IAST> const&) @ 0x000000000f12ed98
  10. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x000000000f6011b0
  11. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000000f5fbeec
  12. DB::InterpreterCreateQuery::execute() @ 0x000000000f607660
  13. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000000fbf0d58
  14. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000000fbed2a8
  15. DB::TCPHandler::runImpl() @ 0x0000000010a02904
  16. DB::TCPHandler::run() @ 0x0000000010a19348
  17. Poco::Net::TCPServerConnection::start() @ 0x0000000012d464b8
  18. Poco::Net::TCPServerDispatcher::run() @ 0x0000000012d46994
  19. Poco::PooledThread::run() @ 0x0000000012e3e718
  20. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000012e3cb10
  21. start_thread @ 0x0000000000007624
  22. ? @ 0x00000000000d162c
```

#### Environment
* dbt version: 1.8.6
* dbt-clickhouse version: 1.8.7
* clickhouse-driver version (if using native): 24.4.1.914
* Python version: Python 3.11.10
* Operating system: macOS Sonoma 14.5

#### ClickHouse server
* ClickHouse Server version: 24.5.8
* `CREATE TABLE` statements for tables involved: See above
