### ISSUE TITLE
adding the ability to authorize via a custom API path

### ISSUE THREAD

**Issue by it-forever** [ClickHouse/dbt-clickhouse#451]
In Clickhouse you can authorize via HTTP, in the current state there is no way to specify a custom API. My configuration:
````
dns_transfer:
  target: dns_transfer
  outputs:
    dns_transfer:
      type: clickhouse
      driver: http
      schema: logging
      host: clickweb.example.com/clickhouse1/ # my test from custom api
      port: 80
      user: user-clickhouse
      password: 'password'
      secure: False
````

configurationg nginx proxy to clickhouse:

````
server {
    listen 80;
    server_name clickweb.example.com;  

    location ~ ^/clickhouse1 {
        rewrite ^/clickhouse1/(.*) /$1 break;
        proxy_pass http://192.168.0.25:8123;
        proxy_redirect http://192.168.0.25:8123/ /;
        proxy_set_header Host $host;
        proxy_connect_timeout 10s;
        proxy_read_timeout 300s;
    }
}

````
when using such a configuration, of course there will be an error connecting to a custom path:

Database Error
  HTTPDriver for http://clickweb.example.com/clickhouse1/:80 returned response code 404

Please add the ability to specify another path url to connect to clickhouse use http port.
