### ISSUE TITLE
JSON not supported in DBT models

### ISSUE THREAD

**Issue by conork92** [ClickHouse/dbt-clickhouse#452]
**Is your feature request related to a problem? Please describe.**
I want to add JSON columns when running models in clickhouse, this works when I run it directly in clcikhouse but when passed in a model I get this error
```
Database Error in model loyalty_reward_opportunities 
  Code: 50.
  DB::Exception: Unsupported type JSON. Stack trace:
``` 

**Describe the solution you'd like**
An a ability to pass a setting that means I can create a model with JSON field

**Comment by morsapaes** [comment]
@conork92, this should already be possible using the `custom_settings` connection configuration:

```yaml
example:
  target: local
  outputs:
    local:
      type: clickhouse
      schema: default
      host: localhost
      port: 9000
      user: default
      password:
      custom_settings: {
            'enable_json_type': 1,
        }
```

Let us know if you're still unable to create models with the new JSON type then. Since JSON support is bound to the database, it should just work with no changes in dbt.
